CREATE SCHEMA cin DEFAULT CHARACTER SET utf8 ;

use cin;

CREATE TABLE Equipamento (
  idEquipamento BIGINT NOT NULL AUTO_INCREMENT,
  tipo INTEGER NOT NULL,
  modelo VARCHAR(255) NOT NULL,
  mesano DATE NOT NULL,
  valor DECIMAL NOT NULL,
  foto LONGBLOB NOT NULL,
  qrcode LONGBLOB NULL,
  PRIMARY KEY(idEquipamento)
);
