CREATE SCHEMA cin DEFAULT CHARACTER SET utf8 ;

use cin;

CREATE TABLE Equipamento (
  id_equipamento BIGINT NOT NULL AUTO_INCREMENT,
  tipo VARCHAR(100) NOT NULL,
  modelo VARCHAR(255) NOT NULL,
  mesano VARCHAR(20) NOT NULL,
  valor DECIMAL NOT NULL,
  foto LONGBLOB NOT NULL,
  PRIMARY KEY(id_equipamento)
);